# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hatservice.proto\"a\n\x12\x43hatMessageRequest\x12\x11\n\tthread_id\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x14\n\x0crecipient_id\x18\x04 \x01(\t\"!\n\x13\x43hatMessageResponse\x12\n\n\x02id\x18\x01 \x01(\x04\"f\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\tthread_id\x18\x02 \x01(\x04\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\tsender_id\x18\x04 \x01(\t\x12\x14\n\x0crecipient_id\x18\x05 \x01(\t\"\"\n\nChatClient\x12\x14\n\x0crecipient_id\x18\x01 \x01(\t\")\n\x14\x44\x65leteAccountRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"#\n\x15\x44\x65leteAccountResponse\x12\n\n\x02id\x18\x01 \x01(\x04\")\n\x14\x43reateAccountRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"#\n\x15\x43reateAccountResponse\x12\n\n\x02id\x18\x01 \x01(\x04\"5\n\x0fWildCardRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07pattern\x18\x02 \x01(\t\"\x1e\n\x10WildCardResponse\x12\n\n\x02id\x18\x01 \x01(\x04\"\"\n\rLogOutRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x1c\n\x0eLogOutResponse\x12\n\n\x02id\x18\x01 \x01(\x04\"!\n\x0cLogInRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x1b\n\rLogInResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x32\xfc\x02\n\x0b\x43hatService\x12\x38\n\x0bSendMessage\x12\x13.ChatMessageRequest\x1a\x14.ChatMessageResponse\x12.\n\x0fReceiveMessages\x12\x0b.ChatClient\x1a\x0c.ChatMessage0\x01\x12>\n\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponse\x12>\n\rDeleteAccount\x12\x15.DeleteAccountRequest\x1a\x16.DeleteAccountResponse\x12/\n\x08WildCard\x12\x10.WildCardRequest\x1a\x11.WildCardResponse\x12)\n\x06LogOut\x12\x0e.LogOutRequest\x1a\x0f.LogOutResponse\x12\'\n\x05LogIn\x12\x0e.LogOutRequest\x1a\x0e.LogInResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATMESSAGEREQUEST._serialized_start=21
  _CHATMESSAGEREQUEST._serialized_end=118
  _CHATMESSAGERESPONSE._serialized_start=120
  _CHATMESSAGERESPONSE._serialized_end=153
  _CHATMESSAGE._serialized_start=155
  _CHATMESSAGE._serialized_end=257
  _CHATCLIENT._serialized_start=259
  _CHATCLIENT._serialized_end=293
  _DELETEACCOUNTREQUEST._serialized_start=295
  _DELETEACCOUNTREQUEST._serialized_end=336
  _DELETEACCOUNTRESPONSE._serialized_start=338
  _DELETEACCOUNTRESPONSE._serialized_end=373
  _CREATEACCOUNTREQUEST._serialized_start=375
  _CREATEACCOUNTREQUEST._serialized_end=416
  _CREATEACCOUNTRESPONSE._serialized_start=418
  _CREATEACCOUNTRESPONSE._serialized_end=453
  _WILDCARDREQUEST._serialized_start=455
  _WILDCARDREQUEST._serialized_end=508
  _WILDCARDRESPONSE._serialized_start=510
  _WILDCARDRESPONSE._serialized_end=540
  _LOGOUTREQUEST._serialized_start=542
  _LOGOUTREQUEST._serialized_end=576
  _LOGOUTRESPONSE._serialized_start=578
  _LOGOUTRESPONSE._serialized_end=606
  _LOGINREQUEST._serialized_start=608
  _LOGINREQUEST._serialized_end=641
  _LOGINRESPONSE._serialized_start=643
  _LOGINRESPONSE._serialized_end=670
  _CHATSERVICE._serialized_start=673
  _CHATSERVICE._serialized_end=1053
# @@protoc_insertion_point(module_scope)
