# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatservice_pb2 as chatservice__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/ChatService/SendMessage',
                request_serializer=chatservice__pb2.ChatMessageRequest.SerializeToString,
                response_deserializer=chatservice__pb2.ChatMessageResponse.FromString,
                )
        self.ReceiveMessages = channel.unary_stream(
                '/ChatService/ReceiveMessages',
                request_serializer=chatservice__pb2.ChatClient.SerializeToString,
                response_deserializer=chatservice__pb2.ChatMessage.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/ChatService/CreateAccount',
                request_serializer=chatservice__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=chatservice__pb2.CreateAccountResponse.FromString,
                )
        self.DeleteAccount = channel.unary_unary(
                '/ChatService/DeleteAccount',
                request_serializer=chatservice__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=chatservice__pb2.DeleteAccountResponse.FromString,
                )
        self.WildCard = channel.unary_unary(
                '/ChatService/WildCard',
                request_serializer=chatservice__pb2.WildCardRequest.SerializeToString,
                response_deserializer=chatservice__pb2.WildCardResponse.FromString,
                )
        self.LogOut = channel.unary_unary(
                '/ChatService/LogOut',
                request_serializer=chatservice__pb2.LogOutRequest.SerializeToString,
                response_deserializer=chatservice__pb2.LogOutResponse.FromString,
                )
        self.LogIn = channel.unary_unary(
                '/ChatService/LogIn',
                request_serializer=chatservice__pb2.LogOutRequest.SerializeToString,
                response_deserializer=chatservice__pb2.LogInResponse.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WildCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogIn(self, request, context):
        """rpc ConnectDuplexStream(stream ChatMessageRequest) returns (stream ChatMessage);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chatservice__pb2.ChatMessageRequest.FromString,
                    response_serializer=chatservice__pb2.ChatMessageResponse.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=chatservice__pb2.ChatClient.FromString,
                    response_serializer=chatservice__pb2.ChatMessage.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=chatservice__pb2.CreateAccountRequest.FromString,
                    response_serializer=chatservice__pb2.CreateAccountResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=chatservice__pb2.DeleteAccountRequest.FromString,
                    response_serializer=chatservice__pb2.DeleteAccountResponse.SerializeToString,
            ),
            'WildCard': grpc.unary_unary_rpc_method_handler(
                    servicer.WildCard,
                    request_deserializer=chatservice__pb2.WildCardRequest.FromString,
                    response_serializer=chatservice__pb2.WildCardResponse.SerializeToString,
            ),
            'LogOut': grpc.unary_unary_rpc_method_handler(
                    servicer.LogOut,
                    request_deserializer=chatservice__pb2.LogOutRequest.FromString,
                    response_serializer=chatservice__pb2.LogOutResponse.SerializeToString,
            ),
            'LogIn': grpc.unary_unary_rpc_method_handler(
                    servicer.LogIn,
                    request_deserializer=chatservice__pb2.LogOutRequest.FromString,
                    response_serializer=chatservice__pb2.LogInResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/SendMessage',
            chatservice__pb2.ChatMessageRequest.SerializeToString,
            chatservice__pb2.ChatMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/ReceiveMessages',
            chatservice__pb2.ChatClient.SerializeToString,
            chatservice__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/CreateAccount',
            chatservice__pb2.CreateAccountRequest.SerializeToString,
            chatservice__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/DeleteAccount',
            chatservice__pb2.DeleteAccountRequest.SerializeToString,
            chatservice__pb2.DeleteAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WildCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/WildCard',
            chatservice__pb2.WildCardRequest.SerializeToString,
            chatservice__pb2.WildCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/LogOut',
            chatservice__pb2.LogOutRequest.SerializeToString,
            chatservice__pb2.LogOutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/LogIn',
            chatservice__pb2.LogOutRequest.SerializeToString,
            chatservice__pb2.LogInResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
